### PR TITLE
Fix methodology

### PR DESCRIPTION
**Pull request by JuliaGreenberg1**
@timathomas I added text describing both geographic and racial 'interpolation' and adjusted some of the other text as well. Let me know what you think! @hmooreo would love your review as well if you have time.

### CODE REVIEW

**Comment by JuliaGreenberg1** [comment]
@timathomas reminder that this still needs to be reviewed and merged!

**Comment by timathomas** [comment]
Yep, been working on it today @JuliaGreenberg1

**Comment by JuliaGreenberg1** [comment]
@timathomas awesome - just wanted to make sure it didn't get lost in all the issues!

**Review by hmooreo — APPROVED** [review]

**Comment by JuliaGreenberg1** [comment]
@hmooreo Can you take a look at the updated `methodology.html` page in the `fix_methodology` branch when you get a chance? I updated the **Deduplication** section.

@timathomas once Hannah has reviewed it's ready for you - I think we should try to publish this as soon as we can so that people can refer to it once the updated profiles are up.

**Comment by timathomas** [comment]
@JuliaGreenberg1 
`index.html` Main is deviated from your branch, particularly index.html. You need to make sure to merge the main into your branch to avoid issues every time you make an edit, or start using sublime merge to follow branch pathways to see where things are going. Go ahead and merge the main into your branch and fix issues any diffs.
`methods.html` Deduplication section is a bit complex. Maybe simplify by avoiding what we found and just stating directly that deduplication cannot be done at some county levels because there's not enough detail however we do deduplicate at the tract level when we have names.

**Comment by JuliaGreenberg1** [comment]
@timathomas I tried simplifying the deduplication section - hopefully there shouldn't be any remaining merge conflicts, let me know if it's still an issue!

**Review by hmooreo — APPROVED** [review]

**Pull request merged**
